version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: todolist
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 4001:80
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
  server:
    build:
      dockerfile: Dockerfile
      context: "../server"
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ../server/src:/app/src
      - ../server/package.json:/app/package.json
      - ../server/tsconfig.json:/app/tsconfig.json
    depends_on:
      - db
    environment:
      CHOKIDAR_USEPOLLING: "true"
  client:
    build:
      dockerfile: Dockerfile
      context: "../client"
    restart: always
    volumes:
      - ../client:/app:delegated
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  dbdata: