on:
    push:
        branches-ignore:
            - master

jobs:
    Install All Packages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: install all packages
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
    
    Code linting app:
        needs: Install All Packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run eslint
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint

    Typings app:
        needs: Code linting app
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run typing app
              uses: borales/actions-yarn@v4
              with:
                  cmd: tsc

    Build app:
        needs: Typings app
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Build the app
              uses: borales/actions-yarn@v4
              with:
                  cmd: build