on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - master
            - dev

jobs:
    install-all-packages-back:
        runs-on: ubuntu-latest
        name: Install All Packages Back
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: install all packages
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
                  dir: 'server'
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: server/node_modules
                  key: ${{ runner.os }}-back-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-back-node-modules-
    
    code-linting-back:
        needs: [install-all-packages-back, install-all-packages-front]
        runs-on: ubuntu-latest
        name: Code linting back
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: server/node_modules
                  key: ${{ runner.os }}-back-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-back-node-modules-
            - name: Run eslint
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint
                  dir: 'server'

    typings-back:
        needs: [code-linting-front, code-linting-back]
        runs-on: ubuntu-latest
        name: Typings back
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: server/node_modules
                  key: ${{ runner.os }}-back-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-back-node-modules-
            - name: Run typing back
              uses: borales/actions-yarn@v4
              with:
                  cmd: tsc
                  dir: 'server'
