on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches:
            - master
            - dev

jobs:
    install-all-packages:
        runs-on: ubuntu-latest
        name: Install All Packages
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Navigate to client directory
              run: |
                  cd client
            - name: install all packages
              uses: borales/actions-yarn@v4
              with:
                  cmd: install
                  dir: 'client'
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
    
    code-linting-app:
        needs: install-all-packages
        runs-on: ubuntu-latest
        name: Code linting app
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Navigate to client directory
              run: |
                  cd client
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run eslint
              uses: borales/actions-yarn@v4
              with:
                  cmd: lint
                  dir: 'client'

    typings-app:
        needs: code-linting-app
        runs-on: ubuntu-latest
        name: Typings app
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Navigate to client directory
              run: |
                  cd client
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Run typing app
              uses: borales/actions-yarn@v4
              with:
                  cmd: tsc
                  dir: 'client'

    build-app:
        needs: typings-app
        runs-on: ubuntu-latest
        name: Building App
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Navigate to client directory
              run: |
                  cd client
            - name: Cache node modules
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-
            - name: Build the app
              uses: borales/actions-yarn@v4
              with:
                  cmd: build
                  dir: 'client'
